# platform :ios, '7.0'
use_frameworks!
target 'GCDFetchFeed' do
	pod 'Reveal-iOS-SDK', :configurations => ['Debug']
	pod 'SDWebImage'
	pod 'Masonry'
	pod 'MJRefresh'
	pod 'JSONModel'
	pod 'Ono'
	pod 'AFNetworking', '=3.0'
	pod 'DTCoreText'
	pod 'FMDB'
	pod 'ReactiveCocoa', '=2.3'
	pod 'FDFullscreenPopGesture'
end