# platform :ios, '7.0'
use_frameworks!
target 'GCDFetchFeed' do
	pod 'SDWebImage'
	pod 'Masonry'
	pod 'MJRefresh'
	pod 'JSONModel'
	pod 'Ono'
	pod 'AFNetworking', '=3.0'
	pod 'DTCoreText'
	pod 'FMDB'
	pod 'ReactiveCocoa', '=2.3'
	pod 'FDFullscreenPopGesture'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
